config/routes.rb
Rails.application.routes.draw do

  scope module: :user do
    root to: 'recruitments#index'
    resources :recruitments
    resources :projects
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  KIND_RECRUITMENT = 1
  KIND_NEWS        = 2

  validates :title,     presence: true
  validates :content,   presence: true
  validates :kind,      presence: true, on: :create
  validates :is_active, presence: false

  belongs_to :project
end

app/models/project.rb
class Project < ApplicationRecord
  #validates :code,            presence: true
  validates :name,            presence: true
  validates :description,     presence: true
  validates :password,        presence: true, length: { minimum: 8 }, on: :create
  validates :owner,           presence: true
  validates :email,           presence: false

  has_secure_password
  has_one :article
  accepts_nested_attributes_for :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/user/application_controller.rb
class User::ApplicationController < ActionController::Base
  layout 'user/layouts/application'
end

app/controllers/user/articles_controller.rb
class User::ArticlesController < User::ApplicationController
  before_action :set_article, only: [:show, :edit, :update]

  # GET /articles
  def index
    @articles = Article.includes(:project).references(:project).where(is_active: true).order('articles.updated_at DESC')
  end

  # GET /articles/1
  def show
  end

  # GET /offers/1/edit
  def edit
  end

  # PATCH/PUT /offers/1
  def update
    if @article.update(article_params)
      redirect_to @article, notice: 'Offer was successfully updated.'
    else
      render :edit
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.includes(:project).references(:project).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:offer).permit(:name)
    end
end

app/controllers/user/comments_controller.rb
class User::CommentsController < User::ApplicationController

  # POST /projects
  def create
    @comment = Comment.new(create_comment_params)

    if @comment.save
      redirect_to recruitment_path, notice: 'プロジェクトを作成しました'
      redirect_back(fallback_location: root_path)
    end
  end

  private

    def create_comment_params
      params.require(:comment).permit(:from, :content)
    end

end

app/controllers/user/offers_controller.rb
class User::OffersController < User::ApplicationController
  before_action :set_offer, only: [:show, :edit, :update, :destroy]

  # GET /offers
  # GET /offers.json
  def index
    @offers = Offer
    .includes(:project).references(:project)
    .includes(project: :owner).references(project: :owner)
    .where(is_active: true)
  end

  # GET /offers/1
  # GET /offers/1.json
  def show
  end

  # GET /offers/new
  def new
    @offer = Offer.new
  end

  # GET /offers/1/edit
  def edit
  end

  # POST /offers
  # POST /offers.json
  def create
    @offer = Offer.new(offer_params)

    respond_to do |format|
      if @offer.save
        format.html { redirect_to @offer, notice: 'Offer was successfully created.' }
        format.json { render :show, status: :created, location: @offer }
      else
        format.html { render :new }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offers/1
  # PATCH/PUT /offers/1.json
  def update
    respond_to do |format|
      if @offer.update(offer_params)
        format.html { redirect_to @offer, notice: 'Offer was successfully updated.' }
        format.json { render :show, status: :ok, location: @offer }
      else
        format.html { render :edit }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1
  # DELETE /offers/1.json
  def destroy
    @offer.destroy
    respond_to do |format|
      format.html { redirect_to offers_url, notice: 'Offer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @offer = Offer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def offer_params
      params.require(:offer).permit(:name)
    end
end

app/controllers/user/projects_controller.rb
class User::ProjectsController < User::ApplicationController

  before_action :set_active_menu
  before_action :set_project, only: [:show, :edit, :update]

  def index
    @projects = Project.order('projects.updated_at DESC')
  end

  def show
  end

  def new
    @project = Project.new
    @project.build_article
  end

  def edit
  end

  def create
    @project = Project.new(create_project_params)

    if @project.save
      redirect_to recruitments_path, notice: 'プロジェクトを作成しました'
    else
      render :new
    end
  end

  def update
    if ! @project.authenticate(params.require(:project).permit(:pass)['pass'])
          return redirect_to edit_project_path(@project), alert: 'パスワードが違います'
    end

    if @project.update(project_params)
      return redirect_to @project, notice: 'プロジェクトを編集しました'
    else
      render :edit
    end
  end

  private
    def set_project
      @project = Project.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:name, :description, :owner, :email)
    end

    def create_project_params
      params.require(:project).permit(:name, :description, :owner, :email, :password, article_attributes: [:title, :content]).to_h.deep_merge(article_attributes: {kind: Article::KIND_RECRUITMENT, is_active: true})
    end

    def set_active_menu
      @activeMenu = 'projects'
    end

end

app/controllers/user/recruitments_controller.rb
class User::RecruitmentsController < User::ApplicationController

  before_action :set_active_menu
  before_action :set_article, only: [:show, :edit, :update]

  def index
    @articles = Article.includes(:project).references(:project).where(is_active: true).order('articles.updated_at DESC')
  end

  def show
  end

  def edit
  end

  def update
    project = Project.find(@article.project.id)
    if ! project.authenticate(params.require(:project).permit(:pass)['pass'])
          return redirect_to edit_recruitment_path(@article), alert: 'パスワードが違います'
    end

    if @article.update(article_params)
      redirect_to recruitment_path(@article), notice: '記事を編集しました'
    else
      render :edit
    end
  end

  private

    def set_article
      @article = Article.includes(:project).references(:project).find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :content, :is_active)
    end

    def set_active_menu
      @activeMenu = 'recruitments'
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user/projects_helper.rb
module User::ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Workspace</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/user/layouts/application.html.erb
<!doctype html>
<html lang="ja" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta http-equiv="Content-Language" content="en" />
    <meta name="msapplication-TileColor" content="#2d89ef">
    <meta name="theme-color" content="#4188c9">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"/>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="HandheldFriendly" content="True">
    <meta name="MobileOptimized" content="320">
    <link rel="icon" href="/favicon.ico" type="image/x-icon"/>
    <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico" />
    <title>制作メンバー募集(β版)</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,300i,400,400i,500,500i,600,600i,700,700i&amp;subset=latin-ext">
    <link href="https://fonts.googleapis.com/css?family=M+PLUS+Rounded+1c" rel="stylesheet">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'user/application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'user/application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="">
    <div class="page">
      <div class="page-main">
        <div class="header py-4">
          <div class="container">
            <div class="d-flex">
              <a class="header-brand" href="/">
                制作メンバー募集(β版)
              </a>
              <div class="d-flex order-lg-2 ml-auto">
              </div>
              <a href="#" class="header-toggler d-lg-none ml-3 ml-lg-0" data-toggle="collapse" data-target="#headerMenuCollapse">
                <span class="header-toggler-icon"></span>
              </a>
            </div>
          </div>
        </div>
        <div class="header collapse d-lg-flex p-0" id="headerMenuCollapse">
          <div class="container">
            <div class="row align-items-center">
              <div class="col-lg order-lg-first">
                <ul class="nav nav-tabs border-0 flex-column flex-lg-row">
                  <li class="nav-item">
                    <a href="<%= projects_path %>" class="nav-link <%= @activeMenu == 'projects' ? 'active' : '' %>"><i class="fe fe-box"></i> プロジェクト一覧</a>
                  </li>
                  <li class="nav-item">
                    <a href="<%= recruitments_path %>" class="nav-link <%= @activeMenu == 'recruitments' ? 'active' : '' %>"><i class="fe fe-inbox"></i> メンバー募集</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div class="my-3 my-md-5">
          <div class="container">
            <% if notice.present? %>
            <div class="alert alert-success" role="alert">
              <%= notice %>
            </div>
            <% end %>
            <% if alert.present? %>
            <div class="alert alert-danger" role="alert">
              <%= alert %>
            </div>
            <% end %>

            <%= yield %>
          </div>
        </div>
      </div>
      <footer class="footer">
        <div class="container">
          <div class="row align-items-center flex-row-reverse">
            <div class="col-auto ml-lg-auto">
            </div>
            <div class="col-12 col-lg-auto mt-3 mt-lg-0 text-center">
              Copyright © 2019 <a href=".">GecoX</a>. Theme by <a href="https://codecalm.net" target="_blank">codecalm.net</a> All rights reserved.
            </div>
          </div>
        </div>
      </footer>
    </div>
  </body>
</html>

app/views/user/projects/edit.html.erb
<div class="page-header">
  <h1 class="page-title">
    メンバー募集作成
  </h1>
</div>

<div class="row row-cards">
  <div class="col-lg-12">
    <%= form_with(model: @project, local: true) do |form| %>
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">プロジェクト</h3>
        </div>
        <div class="card-body">
 
          <div class="col-md-12">
            <div class="form-group">
              <%= form.label :name, :class => 'form-label' do %>プロジェクト名<span class="form-required">*</span><% end %>
              <%= form.text_field :name, class: "form-control #{@project.errors.full_messages_for(:name).any? ? 'is-invalid':''}", placeholder: 'プロジェクト名' %>
              <% @project.errors.full_messages_for(:name).each do |message| %>
                <div class="text-danger"><%= message %></div>
              <% end %>
            </div>
          </div>
  
          <div class="col-md-12">
            <div class="form-group">
              <%= form.label :description, :class => 'form-label' do %>概要<span class="form-required">*</span><% end %>
              <%= form.text_area :description, class: "form-control #{@project.errors.full_messages_for(:description).any? ? 'is-invalid':''}", placeholder: 'プロジェクトの概要を入力してください。', rows: 5 %>
              <% @project.errors.full_messages_for(:description).each do |message| %>
                <div class="text-danger"><%= message %></div>
              <% end %>
            </div>
          </div>

          <div class="col-md-12">
            <div class="form-group">
              <%= form.label :owner, :class => 'form-label' do %>オーナー名<span class="form-required">*</span><% end %>
              <%= form.text_field :owner, class: "form-control #{@project.errors.full_messages_for(:owner).any? ? 'is-invalid':''}", placeholder: 'オーナー名' %>
              <% @project.errors.full_messages_for(:owner).each do |message| %>
                <div class="text-danger"><%= message %></div>
              <% end %>
            </div>
          </div>
  
          <div class="col-md-12">
            <div class="form-group">
              <%= form.label :email, :class => 'form-label' do %>メールアドレス(任意)<% end %>
              <%= form.text_field :email, type: 'email', class: "form-control #{@project.errors.full_messages_for(:email).any? ? 'is-invalid':''}", placeholder: '連絡先として公開されます' %>
              <% @project.errors.full_messages_for(:email).each do |message| %>
                <div class="text-danger"><%= message %></div>
              <% end %>
            </div>
          </div>
 
          <div class="col-md-12">
            <div class="form-group mb-0">
              <label class="form-label" for="project_pass">パスワード<span class="form-required">*</span></label>
              <input type="password" class="form-control " name="project[pass]" id="project_pass">
            </div>
          </div>
  
        </div>

        <div class="card-footer text-right">
          <div class="d-flex">
            <a href="<%= project_path(@project) %>" class="btn btn-link">キャンセル</a>
            <button type="submit" class="btn btn-success ml-auto">プロジェクト編集</button>
          </div>
        </div>

      </div>

    <% end %>
  </div>
</div>

app/views/user/projects/index.html.erb
<div class="page-header">
  <h1 class="page-title"></h1>
</div>

<div class="row row-cards">
  <div class="col-lg-12">
    <div class="card">

      <div class="card-header">
        <h3 class="card-title">プロジェクト一覧</h3>
        <div class="card-options">
          <a href="<%= new_project_path %>" class="btn btn-success btn-sm"><i class="fe fe-plus"></i>プロジェクト作成</a>
        </div>
      </div>

      <div class="table-responsive">
        <table class="table card-table table-striped table-vcenter">
          <thead>
            <tr>
              <th class="">プロジェクト名</th>
              <th class="d-none d-sm-table-cell">オーナー</th>
              <th class="d-none d-md-table-cell">最終更新</th>
            </tr>
          </thead>
          <tbody>
            <% @projects.each do |project| %>
            <tr>
              <td class="text-nowrap"><a href="<%= project_path(project) %>"><%= project.name %></a></td>
              <td class="text-nowrap d-none d-sm-table-cell"><%= project.owner %></td>
              <td class="text-nowrap d-none d-md-table-cell"><%= project.updated_at.strftime("%Y/%m/%d %H:%M") %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>

    </div>
  </div>
</div>

app/views/user/projects/new.html.erb
<div class="page-header">
  <h1 class="page-title">
    メンバー募集作成
  </h1>
</div>

<%= form_with(model: @project, local: true) do |form| %>
<div class="row row-cards">
  <div class="col-lg-6">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title">プロジェクト</h3>
      </div>
      <div class="card-body">
 
        <div class="col-md-12">
          <div class="form-group">
            <%= form.label :name, :class => 'form-label' do %>プロジェクト名<span class="form-required">*</span><% end %>
            <%= form.text_field :name, class: "form-control #{@project.errors.full_messages_for(:name).any? ? 'is-invalid':''}", placeholder: 'プロジェクト名' %>
            <% @project.errors.full_messages_for(:name).each do |message| %>
              <div class="text-danger"><%= message %></div>
            <% end %>
          </div>
        </div>
  
        <div class="col-md-12">
          <div class="form-group">
            <%= form.label :description, :class => 'form-label' do %>概要<span class="form-required">*</span><% end %>
            <%= form.text_area :description, class: "form-control #{@project.errors.full_messages_for(:description).any? ? 'is-invalid':''}", placeholder: 'プロジェクトの概要を入力してください。', rows: 5 %>
            <% @project.errors.full_messages_for(:description).each do |message| %>
              <div class="text-danger"><%= message %></div>
            <% end %>
          </div>
        </div>

         <div class="col-md-12">
          <div class="form-group">
            <%= form.label :owner, :class => 'form-label' do %>オーナー名<span class="form-required">*</span><% end %>
            <%= form.text_field :owner, class: "form-control #{@project.errors.full_messages_for(:owner).any? ? 'is-invalid':''}", placeholder: 'オーナー名' %>
            <% @project.errors.full_messages_for(:owner).each do |message| %>
              <div class="text-danger"><%= message %></div>
            <% end %>
          </div>
        </div>
  
        <div class="col-md-12">
          <div class="form-group">
            <%= form.label :email, :class => 'form-label' do %>メールアドレス(任意)<% end %>
            <%= form.text_field :email, type: 'email', class: "form-control #{@project.errors.full_messages_for(:email).any? ? 'is-invalid':''}", placeholder: '連絡先として公開されます' %>
            <% @project.errors.full_messages_for(:email).each do |message| %>
              <div class="text-danger"><%= message %></div>
            <% end %>
          </div>
        </div>
  
        <div class="col-md-12">
          <div class="form-group mb-0">
            <%= form.label :password, :class => 'form-label' do %>パスワード<span class="form-required">*</span><% end %>
            <%= form.text_field :password, type: 'password', class: "form-control #{@project.errors.full_messages_for(:password).any? ? 'is-invalid':''}" %>
            <span class="small text-muted">編集するときに使用します。</span>
            <% @project.errors.full_messages_for(:password).each do |message| %>
              <div class="text-danger"><%= message %></div>
            <% end %>
          </div>
        </div>
  
      </div>
    </div>
  </div>
  <div class="col-lg-6">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title">メンバー募集記事</h3>
      </div>
      <div class="card-body">
  
        <%= form.fields_for :article do |article| %>
        <div class="col-md-12">
          <div class="form-group">
            <%= article.label :title, :class => 'form-label' do %>募集タイトル<span class="form-required">*</span><% end %>
            <%= article.text_field :title, class: "form-control #{@project.errors.full_messages_for('article.title').any? ? 'is-invalid':''}", placeholder: '募集タイトル' %>
            <% @project.errors.full_messages_for('article.title').each do |message| %>
              <div class="text-danger"><%= message %></div>
            <% end %>
          </div>
        </div>
  
        <div class="col-md-12">
          <div class="form-group">
            <%= article.label :content, :class => 'form-label' do %>募集内容<span class="form-required">*</span><% end %>
            <%= article.text_area :content, class: "form-control #{@project.errors.full_messages_for('article.content').any? ? 'is-invalid':''}", placeholder: '募集内容を入力してください。', rows: 5 %>
            <% @project.errors.full_messages_for('article.content').each do |message| %>
              <div class="text-danger"><%= message %></div>
            <% end %>
          </div>
        </div>
        <% end %>
  
      </div>
  
      <div class="card-footer text-right">
        <div class="d-flex">
          <a href="<%= recruitments_path %>" class="btn btn-link">キャンセル</a>
          <button type="submit" class="btn btn-success ml-auto">作成</button>
        </div>
      </div>
  
    </div>
  </div>
</div>
<% end %>

app/views/user/projects/show.html.erb
<div class="page-header">
  <h1 class="page-title">プロジェクト詳細</h1>
</div>

<div class="row row-cards">
  <div class="col-lg-6">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title">プロジェクト</h3>
        <div class="card-options">
          <a href="<%= edit_project_path(@project) %>" class="btn btn-success btn-sm">編集</a>
        </div>
      </div>
  
      <div class="card-body">
        <div class="row">

          <div class="col-md-12">
            <div class="form-group">
              <label class="form-label">プロジェクト名</label>
              <div class="form-control-plaintext"><%= @project.name %></div>
            </div>
          </div>
   
          <div class="col-md-12">
            <div class="form-group">
              <label class="form-label">概要</label>
              <div class="form-control-plaintext"><pre><%= @project.description %></pre></div>
            </div>
          </div>

          <div class="col-md-12">
            <div class="form-group">
              <label class="form-label">オーナー</label>
              <div class="form-control-plaintext"><%= @project.owner %></div>
            </div>
          </div>
  
          <div class="col-md-12">
            <div class="form-group">
              <label class="form-label">連絡先(メールアドレス)</label>
              <input type="text" class="form-control" value="<%= @project.email %>" onclick="this.select();" readonly>
            </div>
          </div>
   
        </div>
      </div>
  
    </div>
  </div>

  <div class="col-lg-6">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title">
          メンバー募集
          <% if @project.article.is_active %>
              <span class="badge badge-primary">募集中</span>
          <% else %>
              <span class="badge badge-secondary">募集停止中</span>
          <% end %>
        </h3>
        <div class="card-options">
          <a href="<%= edit_recruitment_path(@project) %>" class="btn btn-success btn-sm">編集</a>
        </div>
      </div>
  
      <div class="card-body">
        <div class="row">

          <div class="col-md-12">
            <div class="form-group">
              <label class="form-label">タイトル</label>
              <div class="form-control-plaintext"><%= @project.article.title %></div>
            </div>
          </div>
   
          <div class="col-md-12">
            <div class="form-group">
              <label class="form-label">内容</label>
              <div class="form-control-plaintext"><pre><%= @project.article.content %></pre></div>
            </div>
          </div>

        </div>
      </div>
  
    </div>
  </div>

</div>

app/views/user/recruitments/edit.html.erb
<div class="page-header">
  <h1 class="page-title">
    メンバー募集作成
  </h1>
</div>

<div class="row row-cards">
  <div class="col-lg-12">
    <div class="card">
      <%= form_with(model: @article, url: recruitment_path(@article),  local: true) do |form| %>
        <div class="card-header">
          <h3 class="card-title">メンバー募集記事</h3>
        </div>
        <div class="card-body">
  
          <div class="col-md-12">
            <div class="form-group">
              <%= form.label :is_active, :class => 'form-label' do %>公開・非公開設定<% end %>
              <label class="custom-switch">
                <%= form.check_box :is_active, class: 'custom-switch-input' %>
                <span class="custom-switch-indicator"></span>
                <span class="custom-switch-description">公開する</span>
              </label>
              <% @article.errors.full_messages_for(:is_active).each do |message| %>
                <div class="text-danger"><%= message %></div>
              <% end %>
            </div>
          </div>

          <div class="col-md-12">
            <div class="form-group">
              <%= form.label :title, :class => 'form-label' do %>募集タイトル<span class="form-required">*</span><% end %>
              <%= form.text_field :title, class: "form-control #{@article.errors.full_messages_for(:title).any? ? 'is-invalid':''}", placeholder: '募集タイトル' %>
              <% @article.errors.full_messages_for(:title).each do |message| %>
                <div class="text-danger"><%= message %></div>
              <% end %>
            </div>
          </div>
  
          <div class="col-md-12">
            <div class="form-group">
              <%= form.label :content, :class => 'form-label' do %>募集内容<span class="form-required">*</span><% end %>
              <%= form.text_area :content, class: "form-control #{@article.errors.full_messages_for(:content).any? ? 'is-invalid':''}", placeholder: '募集内容を入力してください。', rows: 5 %>
              <% @article.errors.full_messages_for(:content).each do |message| %>
                <div class="text-danger"><%= message %></div>
              <% end %>
            </div>
          </div>

          <div class="col-md-12">
            <div class="form-group mb-0">
              <label class="form-label" for="project_pass">パスワード<span class="form-required">*</span></label>
              <input type="password" class="form-control " name="project[pass]" id="project_pass">
            </div>
          </div>
   
        </div>
  
        <div class="card-footer text-right">
          <div class="d-flex">
            <a href="<%= project_path(@article.project) %>" class="btn btn-link">キャンセル</a>
            <button type="submit" class="btn btn-success ml-auto">編集</button>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/user/recruitments/index.html.erb
<div class="page-header">
  <h1 class="page-title">
    メンバー募集
  </h1>
  <a href="<%= new_project_path %>" class="btn btn-success btn-sm ml-auto"><i class="fe fe-plus"></i>プロジェクト作成</a>
</div>

<div class="row row-cards row-deck">

  <% @articles.each do |article| %>
  <div class="col-lg-4">
    <div class="card">
      <div class="card-body d-flex flex-column">
        <h4><a href="<%= recruitment_path(article) %>"><%= article.title %></a></h4>
        <div class="text-muted"><%= article.content %></div>
        <div class="d-flex align-items-center pt-5 mt-auto">
          <div>
            <a href="./profile.html" class="text-default"><%= article.project.owner %></a>
            <small class="d-block text-muted"><%= article.updated_at.strftime("%Y/%m/%d %H:%M") %></small>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/user/recruitments/show.html.erb
<div class="page-header">
  <h1 class="page-title">募集詳細</h1>
</div>

<div class="row row-cards">

  <div class="col-lg-6">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title">
          メンバー募集
          <% if @article.is_active %>
              <span class="badge badge-primary">募集中</span>
          <% else %>
              <span class="badge badge-secondary">募集停止中</span>
          <% end %>
        </h3>
        <div class="card-options">
          <a href="<%= edit_recruitment_path(@article) %>" class="btn btn-success btn-sm">編集</a>
        </div>
      </div>
  
      <div class="card-body">
        <div class="row">

          <div class="col-md-12">
            <div class="form-group">
              <label class="form-label">タイトル</label>
              <div class="form-control-plaintext"><%= @article.title %></div>
            </div>
          </div>
   
          <div class="col-md-12">
            <div class="form-group">
              <label class="form-label">内容</label>
              <div class="form-control-elaintext"><pre><%= @article.content %></pre></div>
            </div>
          </div>

        </div>
      </div>
  
    </div>
  </div>


  <div class="col-lg-6">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title">プロジェクト</h3>
        <div class="card-options">
          <a href="<%= edit_project_path(@article) %>" class="btn btn-success btn-sm">編集</a>
        </div>
      </div>
  
      <div class="card-body">
        <div class="row">

          <div class="col-md-12">
            <div class="form-group">
              <label class="form-label">プロジェクト名</label>
              <div class="form-control-plaintext"><%= @article.project.name %></div>
            </div>
          </div>
   
          <div class="col-md-12">
            <div class="form-group">
              <label class="form-label">概要</label>
              <div class="form-control-plaintext"><pre><%= @article.project.description %></pre></div>
            </div>
          </div>

          <div class="col-md-12">
            <div class="form-group">
              <label class="form-label">オーナー</label>
              <div class="form-control-plaintext"><%= @article.project.owner %></div>
            </div>
          </div>
  
          <div class="col-md-12">
            <div class="form-group">
              <label class="form-label">連絡先(メールアドレス)</label>
              <input type="text" class="form-control" value="<%= @article.project.email %>" onclick="this.select();" readonly>
            </div>
          </div>
   
        </div>
      </div>
  
    </div>
  </div>

</div>